import { randomUUID } from "node:crypto";
import { test, expect, type Page } from "@playwright/test";
import { parseScore, type LeadSheet } from "../../contracts/src/index";
test.use({ trace: "off" });

async function savedScore(page: Page): Promise<LeadSheet> {
  const save = page.getByRole("button", { name: "Save sheet", exact: true });
  if (await save.isEnabled()) { await save.click(); await expect(save).toBeDisabled(); }
  const list = await (await page.request.get("/api/v1/sheets")).json();
  const saved = await (await page.request.get(`/api/v1/sheets/${list.sheets[0].id}`)).json();
  return parseScore(saved.score);
}

test("continuous chord and direct stave entry preserve exact edits through save and reopen", async ({ page }) => {
  test.setTimeout(90_000);
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto("/");
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await page.getByLabel("Name", { exact: true }).fill("Fast entry acceptance");
  await page.getByLabel("Email", { exact: true }).fill(`entry-${randomUUID()}@example.test`);
  await page.getByLabel("Password", { exact: true }).fill(`Entry-${randomUUID()}`);
  await page.getByRole("button", { name: "Create your account", exact: true }).click();
  await page.getByRole("button", { name: "New sheet", exact: true }).click();
  const title = `Fast entry ${randomUUID().slice(0, 8)}`;
  await page.getByLabel("Sheet title", { exact: true }).fill(title);
  await page.getByRole("button", { name: "Create and save sheet", exact: true }).click();
  const recent = page.getByLabel("Recent and pinned chords");
  await recent.getByRole("button", { name: "C", exact: true }).click();
  await recent.getByRole("button", { name: "G", exact: true }).click();
  await expect(page.getByLabel("Chord keyboard")).toBeVisible();
  let score = await savedScore(page);
  expect(score.measures.slice(0, 2).map(m => m.chords.map(c => c.symbol))).toEqual([["C"], ["G"]]);
  await page.getByLabel("Insertion bar", { exact: true }).selectOption("0");
  await page.getByRole("button", { name: "Insert at bar 1 beat 3", exact: true }).click();
  await recent.getByRole("button", { name: "Am", exact: true }).click();
  score = await savedScore(page);
  expect(score.measures[0].chords.map(c => [c.symbol, c.durationTicks])).toEqual([["C", 960], ["Am", 960]]);
  await page.getByRole("button", { name: "+ Bar", exact: true }).click();
  const source = page.locator('[data-entry-bar="1"] .editable-chord'), target = page.locator('[data-entry-bar="2"]');
  const sourceBox = (await source.boundingBox())!, targetBox = (await target.boundingBox())!;
  await page.mouse.move(sourceBox.x + sourceBox.width / 2, sourceBox.y + sourceBox.height / 2); await page.mouse.down();
  await page.mouse.move(targetBox.x + 2, targetBox.y + 50, { steps: 10 }); await page.mouse.up();
  const movedChord = await savedScore(page);
  expect(movedChord.measures[1].chords).toEqual([]);
  expect(movedChord.measures[2].chords[0]).toEqual(score.measures[1].chords[0]);
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  expect(await savedScore(page)).toEqual(score);
  await page.getByRole("button", { name: "Melody entry", exact: true }).click();
  const cursor = page.getByRole("button", { name: "Next note entry line", exact: true });
  await expect(cursor).toBeVisible();
  await expect(page.getByLabel("Insertion bar", { exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Hide tutorial", exact: true })).toHaveCount(0);
  await expect(page.locator(".notation svg")).toHaveCount(1);
  await cursor.click({ position: { x: 20, y: 55 } });
  score = await savedScore(page);
  const original = score.measures[0].melody[0];
  expect(original).toMatchObject({ offsetTicks: 0, pitch: { step: "E", octave: 4 } });
  await cursor.click({ position: { x: 20, y: 45 } });
  await page.getByRole("button", { name: "Insert rest", exact: true }).click();
  score = await savedScore(page);
  expect(score.measures[0].melody.map(n => [n.offsetTicks, n.kind])).toEqual([[0, "note"], [480, "note"], [960, "rest"]]);
  const notehead = page.locator(".notation .vf-notehead").first();
  let head = (await notehead.boundingBox())!;
  await page.mouse.move(head.x + head.width / 2, head.y + head.height / 2); await page.mouse.down();
  await page.mouse.move(head.x + head.width / 2 + 20, head.y + head.height / 2 - 20, { steps: 6 }); await page.mouse.up();
  score = await savedScore(page);
  expect(score.measures[0].melody[0]).toMatchObject({ id: original.id, offsetTicks: 0, duration: original.duration });
  expect(score.measures[0].melody[0]).not.toEqual(original);
  const beforeCancel = score;
  head = (await notehead.boundingBox())!;
  await page.mouse.move(head.x + head.width / 2, head.y + head.height / 2); await page.mouse.down();
  await page.mouse.move(head.x + 10, head.y - 25, { steps: 5 });
  await page.keyboard.press("Escape"); await page.mouse.up();
  expect(await savedScore(page)).toEqual(beforeCancel);
  const duration = page.getByRole("slider", { name: "Selected note duration", exact: true });
  await duration.focus(); await duration.press("ArrowRight"); await duration.press("ArrowRight");
  score = await savedScore(page);
  expect(score.measures[0].melody.map(n => n.offsetTicks)).toEqual([0, 960, 1440]);
  expect(score.measures[0].melody[0].duration).toEqual({ denominator: 2, dots: 0 });
  const afterResize = score;
  await expect(page.getByText(/Local recovery copy updated|Writing local recovery copy/)).toHaveCount(0);
  expect(await duration.evaluate(el => !!el.closest('.inline-note-tools'))).toBe(true);
  await page.getByRole("button", { name: "Delete selected note", exact: true }).click();
  score = await savedScore(page);
  expect(score.measures[0].melody.map(n => n.offsetTicks)).toEqual([0, 480]);
  expect(score.measures.flatMap(m => m.melody).some(n => n.id === original.id)).toBe(false);
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  expect(await savedScore(page)).toEqual(afterResize);
  await page.locator(`[data-note-id="${original.id}"]`).click();
  await page.getByRole("button", { name: "Replace selected note with rest", exact: true }).click();
  score = await savedScore(page);
  expect(score.measures[0].melody[0]).toMatchObject({ kind: "rest", id: original.id, duration: { denominator: 2, dots: 0 } });
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  expect(await savedScore(page)).toEqual(afterResize);
  await cursor.click({ position: { x: 20, y: 40 } });
  score = await savedScore(page);
  expect(score.measures[1].melody[0]).toMatchObject({ offsetTicks: 0 });
  await expect(page.getByRole("slider")).toHaveCount(1);
  await expect(page.getByRole("button", { name: /^(Move|Length|Add note by hand|Change last)$/ })).toHaveCount(0);
  const beforeSave = await page.getByTestId("notation").boundingBox();
  await savedScore(page);
  expect((await page.getByTestId("notation").boundingBox())!.y).toBe(beforeSave!.y);
  await page.reload(); await page.getByRole("button", { name: `Edit ${title}`, exact: true }).click();
  expect(await savedScore(page)).toEqual(score);
  await page.getByRole("button", { name: "Melody entry", exact: true }).click();
  await expect(page.locator(".editable-melody")).toHaveCount(4);
  await page.setViewportSize({ width: 1280, height: 800 });
  await expect(cursor).toBeInViewport();
  await page.screenshot({ path: "docs/architecture/evidence/fast-entry-web.png" });
  await page.setViewportSize({ width: 360, height: 800 });
  await cursor.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "docs/architecture/evidence/fast-entry-web-narrow.png" });
  expect(errors).toEqual([]);
});
