import { randomUUID } from "node:crypto";
import { test, expect } from "@playwright/test";

test("Library organization remains recoverable and Practice does not edit notation", async ({ page }) => {
  test.setTimeout(75_000);
  await page.goto("/");
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await page.getByLabel("Name", { exact: true }).fill("Practice tester");
  await page.getByLabel("Email", { exact: true }).fill(`practice-${randomUUID()}@example.test`);
  await page.getByLabel("Password", { exact: true }).fill("Local-piano-test-2026!");
  await page.getByRole("button", { name: "Create your account" }).click();
  await page.getByRole("button", { name: "New sheet", exact: true }).click();
  const form = page.getByRole("form", { name: "New sheet" });
  await form.getByLabel("Sheet title").fill("Library practice original");
  await form.getByLabel("A copy of the original example").check();
  await form.getByRole("button", { name: "Create and save sheet" }).click();
  await expect(page.getByTestId("notation")).toHaveAttribute("data-rendered", "true");
  await page.getByRole("button", { name: "Sheet details" }).click();
  await page.getByLabel("YouTube tutorial link").fill("https://youtu.be/dQw4w9WgXcQ");
  await page.getByRole("button", { name: "Save details" }).click();
  const initialSheets = await (await page.request.get("/api/v1/sheets")).json();
  const originalId = initialSheets.sheets.find((value: { title: string }) => value.title === "Library practice original").id;
  const authored = await (await page.request.get(`/api/v1/sheets/${originalId}`)).json();
  await page.getByRole("button", { name: "Library", exact: true }).click();
  const card = page.getByRole("article").filter({ has: page.getByRole("heading", { name: "Library practice original", exact: true }) });
  await card.getByRole("button", { name: "Favorite Library practice original" }).click();
  await card.locator("summary").click();
  await card.getByRole("button", { name: "Mark draft" }).click();
  await page.getByRole("button", { name: "Favorites", exact: true }).click();
  await expect(card).toBeVisible();
  await page.getByRole("button", { name: "Drafts", exact: true }).click();
  await expect(card).toBeVisible();
  if (process.env.CHORDVIEWER_CAPTURE_EVIDENCE === "1") {
    await page.getByRole("button", { name: "All", exact: true }).click();
    await page.setViewportSize({ width: 1280, height: 950 });
    await page.evaluate(() => document.fonts.ready);
    await page.screenshot({ path: "docs/architecture/evidence/m6-web-library.png", fullPage: true });
    await page.setViewportSize({ width: 1280, height: 720 });
    await page.getByRole("button", { name: "Drafts", exact: true }).click();
  }
  await page.getByLabel("Search sheets").fill("missing title");
  await expect(card).toBeHidden();
  await page.getByLabel("Search sheets").fill("");
  await card.getByRole("button", { name: "Practice Library practice original" }).click();
  await expect(page.getByText("Read only", { exact: false })).toBeVisible();
  await expect(page.getByRole("button", { name: "Manual" })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "On match" }).click();
  await page.getByRole("button", { name: "Next bar" }).click();
  await expect(page.getByText("Bar 2 of 4")).toBeVisible();
  await page.getByLabel("Transpose").selectOption("2");
  await expect(page.getByRole("heading", { name: "Library practice original" })).toBeVisible();
  await page.getByRole("button", { name: "Smaller score" }).click();
  await expect(page.getByText("90%")).toBeVisible();
  await page.getByRole("button", { name: "Play tutorial" }).click();
  await expect(page.locator("iframe.tutorial-player")).toHaveAttribute("src", /youtube\.com\/embed\/dQw4w9WgXcQ/);
  if (process.env.CHORDVIEWER_CAPTURE_EVIDENCE === "1") {
    await page.evaluate(() => document.fonts.ready);
    await page.screenshot({ path: "docs/architecture/evidence/m6-web-practice.png", fullPage: true });
    await page.setViewportSize({ width: 760, height: 900 });
    const tabletPlayer = await page.locator("iframe.tutorial-player").boundingBox();
    const tabletCard = await page.locator(".tutorial-card").boundingBox();
    expect(tabletPlayer?.width).toBeGreaterThanOrEqual(200);
    expect(tabletPlayer?.x).toBeGreaterThanOrEqual(tabletCard!.x);
    expect(tabletPlayer!.x + tabletPlayer!.width).toBeLessThanOrEqual(tabletCard!.x + tabletCard!.width);
    await page.screenshot({ path: "docs/architecture/evidence/m6-web-practice-tablet.png", fullPage: true });
    await page.setViewportSize({ width: 360, height: 900 });
    const player = await page.locator("iframe.tutorial-player").boundingBox();
    expect(player?.width).toBeGreaterThanOrEqual(200);
    expect(player?.height).toBeGreaterThanOrEqual(200);
    const scoreBody = await page.locator(".practice-sheet-panel .sheet-body").boundingBox();
    expect(scoreBody?.height).toBeGreaterThanOrEqual(260);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: "docs/architecture/evidence/m6-web-practice-narrow.png", fullPage: true });
    await page.setViewportSize({ width: 1280, height: 720 });
  }
  await page.getByRole("button", { name: "Hide tutorial" }).click();
  await expect(page.locator("iframe.tutorial-player")).toHaveCount(0);
  await page.getByRole("button", { name: "Edit sheet" }).click();
  await expect(page.getByLabel("Insertion bar")).toHaveValue("1");
  const unchanged = await (await page.request.get(`/api/v1/sheets/${originalId}`)).json();
  expect(unchanged.score).toEqual(authored.score);
  expect(unchanged.revision).toBe(authored.revision + 2); // favorite and Draft are guarded metadata revisions
  await page.getByRole("button", { name: "Library", exact: true }).click();
  await expect(page.locator("iframe.tutorial-player")).toHaveCount(0);
  await page.getByRole("button", { name: "All", exact: true }).click();
  await card.getByRole("button", { name: "Edit Library practice original" }).click();
  await expect(page.getByLabel("Insertion bar")).toHaveValue("1");
  await page.getByRole("button", { name: "Library", exact: true }).click();
  if (await card.locator("details").getAttribute("open") === null) await card.locator("summary").click();
  await card.getByRole("button", { name: "Duplicate" }).click();
  const copy = page.getByRole("article").filter({ has: page.getByRole("heading", { name: "Library practice original (copy)", exact: true }) });
  await expect(copy).toBeVisible();
  await copy.getByRole("button", { name: "Practice Library practice original (copy)" }).click();
  await expect(page.getByText("Bar 1 of 4")).toBeVisible();
  await page.getByRole("button", { name: "Library", exact: true }).click();
  await card.getByRole("button", { name: "Practice Library practice original" }).click();
  await expect(page.getByText("Bar 2 of 4")).toBeVisible();
  await page.getByRole("button", { name: "Library", exact: true }).click();
  if (await card.locator("details").getAttribute("open") === null) await card.locator("summary").click();
  await card.getByRole("button", { name: "Move to Trash" }).click();
  await page.getByRole("button", { name: "Trash", exact: true }).click();
  await expect(card.getByRole("button", { name: "Restore" })).toBeVisible();
  await card.getByRole("button", { name: "Restore" }).click();
  await page.getByRole("button", { name: "All", exact: true }).click();
  await expect(card.getByRole("button", { name: "Practice Library practice original" })).toBeVisible();
});

test("Trash remains reachable when the only active sheet is moved there", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: "Create account", exact: true }).click();
  await page.getByLabel("Name", { exact: true }).fill("Trash tester");
  await page.getByLabel("Email", { exact: true }).fill(`trash-${randomUUID()}@example.test`);
  await page.getByLabel("Password", { exact: true }).fill("Local-piano-test-2026!");
  await page.getByRole("button", { name: "Create your account" }).click();
  await page.getByRole("button", { name: "New sheet", exact: true }).click();
  const form = page.getByRole("form", { name: "New sheet" });
  await form.getByLabel("Sheet title").fill("Recover me");
  await form.getByRole("button", { name: "Create and save sheet" }).click();
  await page.getByRole("button", { name: "Library", exact: true }).click();
  const card = page.getByRole("article").filter({ has: page.getByRole("heading", { name: "Recover me" }) });
  await card.locator("summary").click();
  await card.getByRole("button", { name: "Move to Trash" }).click();
  await expect(page.getByRole("button", { name: "Trash", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Trash", exact: true }).click();
  await card.getByRole("button", { name: "Restore" }).click();
  await page.getByRole("button", { name: "All", exact: true }).click();
  await expect(card.getByRole("button", { name: "Edit Recover me" })).toBeVisible();
});
